server:
  port: 7001
eureka:
  instance:
    #单机模式
    #hostname: localhost   #eureka服务端的实例名称
    #集群模式
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: false   #false表示不想注册中心注册自己
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true       #false表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检查服务
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone:  http://eureka7001.com:7001/eureka/
      #集群模式
      #defaultZone:  http://eureka7002.com:7002/eureka/
  server:
    #关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000