server:
  port: 3344
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:cheungyutong/common-config.git
          search-paths:
            - common-config
      label: master

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka  #单机版
      #defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版
  instance:
    #设置实例的id
    #instance-id: config
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds:  1
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 1