server:
  port: 8001
spring:
  application:
    name: cloud-hystrix-provider
eureka:
  client:
    register-with-eureka: true    #表示是否将自己注册进EurekaServer默认为true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须配置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone:  http://localhost:7001/eureka
      #集群版
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
instance:
  #设置实例的id
  #instance-id: payment8001
  #访问路径可以显示IP地址
  prefer-ip-address: true
  #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
  lease-renewal-interval-in-seconds:  1
  #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认90秒），超时将剔除服务
  lease-expiration-duration-in-seconds: 1