server:
  port: 8803

spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: 39.106.151.228
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          #设置消费者分组，分组不同，会重复消费
          group: cheungyutong
eureka:
  client:
    register-with-eureka: true    #表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须配置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone:  http://localhost:7001/eureka  #单机版
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版
  instance:
    #设置实例的id
    #instance-id: consumer8803
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds:  1
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 1