server:
  port: 80
spring:
  application:
    name: cloud-feign-order
eureka:
  client:
    register-with-eureka: true
    service-url:
      #单机版
      #defaultZone:  http://localhost:7001/eureka
      #集群版
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #设置实例的id
    #instance-id: order80
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds:  1
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 1
#设置feign客户端超时时间(openfeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout:  5000
#指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控哪个端口
    com.cheungyutong.service.PaymentFeignService: debug